name: Terraform Destroy
run-name: Terraform destroy ${{ inputs.workspace }} by @${{ github.actor }}

#checkov:skip=CKV_GHA_7:workflow_dispatch input required by design
on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'The workspace to terraform against (dev is the only valid option)'
        required: true
        type: choice
        options:
          - dev

concurrency:
  group: ${{ github.event.inputs.workspace }}-terraform
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

env:
  workspace: ${{ github.event.inputs.workspace }}

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.workspace == 'dev' }}
    environment: Dev
    defaults:
      run:
        shell: bash
        working-directory: terraform/implementation/ecs
    steps:
      - name: Check Out Changes
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: configure aws dev credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_DEV_ROLE_ARN }}
          role-session-name: githubDeploymentWorkflow
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform
        env:
          BUCKET: ${{ vars.TFSTATE_BUCKET }}
          DYNAMODB_TABLE: ${{ vars.TFSTATE_DYNAMODB_TABLE }}
          REGION: ${{ vars.AWS_REGION }}
          WORKSPACE: ${{ env.workspace }}
          TF_VAR_sql_connection_string: ${{ secrets.DEV_SQL_CONNECTION_STRING }}
          TF_VAR_nextauth_secret: ${{ secrets.DEV_NEXTAUTH_SECRET }}
          TF_VAR_auth_client_secret: ${{ secrets.DEV_AUTH_CLIENT_SECRET }}
        shell: bash
        run: |
          terraform init \
            -var-file="$WORKSPACE.tfvars" \
            -backend-config "bucket=$BUCKET" \
            -backend-config "dynamodb_table=$DYNAMODB_TABLE" \
            -backend-config "region=$REGION" \
            || (echo "terraform init failed, exiting..." && exit 1)
          rm -rf .terraform/modules/ecs/.git
          terraform workspace select "$WORKSPACE"
          terraform plan -destroy -var-file="$WORKSPACE.tfvars"
          terraform destroy -auto-approve -var-file="$WORKSPACE.tfvars"
